services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - GATEWAY_SERVER_ADDR=gateway:9091
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
    depends_on:
      - gateway

  gateway:
    build:
      context: gateway
      target: builder
    stop_signal: SIGINT
    environment:
      - GATEWAY_SERVER_PORT=9091
    volumes:
      - ./gateway:/src
    depends_on:
      -  mongo

  mongo:
    image: mongo